# Generated by Django 2.1.3 on 2018-11-25 03:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onePinasModel', '0007_auto_20181125_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhancement', models.CharField(max_length=1000)),
                ('priority_points', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 11, 26, 48, 544153)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 11, 26, 48, 544950)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 25, 11, 26, 48, 548592)),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onePinasModel.Task'),
        ),
    ]
