# Generated by Django 2.1.3 on 2018-11-24 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, null=True)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('account_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 2, 29, 524184))),
                ('is_deleted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('industry', models.CharField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('contact_number', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('website', models.CharField(max_length=1000, null=True)),
                ('about', models.CharField(max_length=1000, null=True)),
                ('mission', models.CharField(max_length=1000, null=True)),
                ('vision', models.CharField(max_length=1000, null=True)),
                ('history', models.CharField(max_length=1000, null=True)),
                ('summary', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.DateField()),
                ('date_resigned', models.DateField()),
                ('is_resigned', models.IntegerField()),
                ('reason_for_leaving', models.CharField(max_length=1000, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onePinasModel.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('requirements', models.CharField(max_length=1000, null=True)),
                ('salary', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 2, 29, 524888))),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('schedule', models.CharField(max_length=1000, null=True)),
                ('associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onePinasModel.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_received', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 2, 29, 526377))),
                ('message', models.CharField(max_length=1000, null=True)),
                ('is_attachment', models.IntegerField()),
                ('is_image', models.IntegerField()),
                ('seen', models.IntegerField()),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=1000, null=True)),
                ('first_name', models.CharField(max_length=1000, null=True)),
                ('middle_name', models.CharField(max_length=1000, null=True)),
                ('contact_number', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('street_number', models.CharField(max_length=1000, null=True)),
                ('baranggay', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=1000, null=True)),
                ('province', models.CharField(max_length=1000, null=True)),
                ('region', models.CharField(max_length=1000, null=True)),
                ('birthday', models.CharField(max_length=1000, null=True)),
                ('gender', models.CharField(max_length=1000, null=True)),
                ('civil_status', models.CharField(max_length=1000, null=True)),
                ('citizenship', models.CharField(max_length=1000, null=True)),
                ('disability', models.CharField(max_length=1000, null=True)),
                ('sss', models.CharField(max_length=1000, null=True)),
                ('philhealth', models.CharField(max_length=1000, null=True)),
                ('tin', models.CharField(max_length=1000, null=True)),
                ('pagibig', models.CharField(max_length=1000, null=True)),
                ('is_verified', models.IntegerField()),
                ('is_employed', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employments',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onePinasModel.Job'),
        ),
        migrations.AddField(
            model_name='account',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onePinasModel.Business'),
        ),
    ]
