# Generated by Django 2.1.3 on 2018-11-24 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePinasModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employments',
            new_name='Employment',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 16, 10, 633603)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 16, 10, 634305)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 16, 10, 636108)),
        ),
    ]
